version: '3'
services:
  spider:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    network_mode: "bridge"
    container_name: php
    image: adrian812/nginx-php7
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /var/www:/var/www
    ports:
      - "80:80"
