version: '3'
services:
  fn:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    network_mode: "bridge"
    container_name: fn
    image: adrian812/nginx-php7
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /data/www/fn:/var/www/html
    ports:
      - "80:80"
      - "8080:8080"
      - "8081:8081"
